translation:
  eke_to_eng: 'Translate the following Ekegusii text into English:


    Input: {src}


    Output:'
  eke_to_swa: 'Translate the following Ekegusii text into Kiswahili:


    Input: {src}


    Output:'
  eng_to_eke: 'Translate the following English text into Ekegusii:


    Input: {src}


    Output:'
  swa_to_eke: 'Translate the following Kiswahili text into Ekegusii:


    Input: {src}


    Output:'
  eng_to_swa: 'Translate the following English text into Kiswahili:


    Input: {src}


    Output:'
  swa_to_eng: 'Translate the following Kiswahili text into English:


    Input: {src}


    Output:'
  system_prompt: You are an expert translator specializing in low-resource African
    languages.
