model:
  name_or_path: Qwen/Qwen2.5-7B-Instruct
  torch_dtype: bfloat16
  use_fast_tokenizer: true
qlora:
  lora_alpha: 64
  lora_dropout: 0.05
  r: 32
  target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
training:
  gradient_accumulation_steps: 8
  learning_rate: 0.0002
  lr_scheduler_type: cosine
  num_train_epochs: 4
  optim: paged_adamw_8bit
  per_device_train_batch_size: 4
  warmup_ratio: 0.1
